### ISSUE TITLE
Inkscape not found on Windows path

### ISSUE THREAD

**Issue by rodrigopitanga** [borgand/inkscape_merge#12]
I'm trying to run inkscape_merge on Windows 10. Inkscape is installed with default settings (system install, not unzipped). This is what I get.

```
C:\xxxxx>inkscape_merge -d dados.csv -f modelos/modelo_adm18.svg -o crachas/%VAR_nome%.pdf --dpi 600
Traceback (most recent call last):
        5: from C:/Ruby25-x64/bin/inkscape_merge:23:in `<main>'
        4: from C:/Ruby25-x64/bin/inkscape_merge:23:in `load'
        3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inkscape_merge-0.3.0/bin/inkscape_merge:7:in `<top (required)>'
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inkscape_merge-0.3.0/bin/inkscape_merge:7:in `new'
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inkscape_merge-0.3.0/lib/inkscape_merge/processor.rb:21:in `initialize'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inkscape_merge-0.3.0/lib/inkscape_merge/processor.rb:21:in ``': No such file or directory - which inkscape (Errno::ENOENT)

C:\xxxxx>which
'which' is not recognized as an internal or external command,
operable program or batch file.
```
Obviously Windows does not have `which`. I'm not actually a Windows user so not sure how to fix this.

**Comment by eagleonfire** [comment]
Did you find a resolution to this? I am having the same problem.

**Comment by blump-k** [comment]
Likewise! I'm having the same issue. Any recommendations?

**Comment by eagleonfire** [comment]
@blump-k  the only way I was able to get this working on Windows 10 was to install the Linux subsystem, Ubuntu 18.04, then install Inkscape, add the Inkscape Generator.tgz and put the files in the right places (don't forget permissions).  http://wiki.colivre.net/Aurium/InkscapeGenerator    Next add an Xserver. I used Xming.  Start up Ubuntu, start Xming, go into Ubuntu export LIBGL_ALWAYS_INDIRECT=1  then export DISPLAY=:0 then start inkscape. If you have done everything right you will see the the Generator under Misc in the Inkscape extension menu drop down.  When you run it you will need to use paths to get to your .csv file and set output parameters. 
I found the image http://wiki.colivre.net/pub/Aurium/InkscapeGenerator/screenshot-direct-mailing.png  helpful, but the output path for Windows doesn't use the $ at the front. 

I actually use Inkscape on Windows to build the SVG, then open it in Inkscape under Ubuntu to do the merge. In the Generator I use the path /mnt/c/Users/"username"/Desktop ...  to spit all the merge images back to my Windows Desktop.   Good luck.
